```{r}
library(tidyverse)
```

```{r}
livestream_data <- read_csv("data/synthesised_livestream.csv")
survey_data <- read_csv("data/clean_survey_data.csv")
location_data <- read_csv("data/location_distance_count.csv")
```

```{r}
# graph sorting and counting respondents by residence
survey_data %>% 
  select(residence) %>% 
  count(residence, sort = TRUE) %>% 
  ggplot() +
  geom_col(aes(x = residence, y = n), fill = "#008b8b") +
  labs(
    title = "Where Respondents Travelled From",
    x = "Residence",
    y = "Count"
  ) +
 theme_classic(base_size = 15) +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
# reversing the vector so that the flipped graph labels are alphabetical from A-Z
local_authority_vector_rev <- rev(local_authority_vector)
```

```{r}
# sorting and counting data by local authority (for respondents resident in Scotland)
survey_data %>% 
 filter(residence == "scotland") %>% 
  filter(local_authority != "unknown") %>% 
  count(local_authority, sort = TRUE) %>% 
    mutate(name = factor(local_authority, levels = local_authority_vector_rev)) %>% 
  ggplot() +
  geom_col(aes(x = name, y = n), fill = "#008b8b") +
  coord_flip() +
  labs(title = "Respondents in Scotland by Local Authority",
      x = "Local Authority", y = "Count") +
   theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 15)
```

```{r}
# graph of types of transport used to travel to the event
survey_data %>% 
  count(event_travel, sort = TRUE) %>% 
  filter(n >= 5) %>% 
  ggplot() +
  geom_col(aes(x = event_travel, y = n),fill = "#008b8b") +
  coord_flip() +
  labs(title = "Travel During Event",
       x = "Travel Method,",
       y = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 15)
```
```{r}
# graph of types of transport used during the event
survey_data %>% 
  count(event_travel, sort = TRUE) %>% 
  filter(n >= 5) %>% 
  ggplot() +
  geom_col(aes(x = event_travel, y = n),fill = "#008b8b") +
  coord_flip() +
  labs(title = "Travel During Event",
       x = "Travel Method",
       y = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic(base_size = 15)
```

```{r}
# splitting distances gained from the google map distance API into categories
hundred_and_over <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 100) %>% 
  nrow()

ninety_to_hundred <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 90 & miles < 100) %>% 
  nrow()

eighty_to_ninety <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 80 & miles < 90) %>% 
  nrow()

seventy_to_eighty <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 70 & miles < 80) %>% 
  nrow()

sixty_to_seventy <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 60 & miles < 70) %>% 
  nrow()

fifty_to_sixty <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 50 & miles < 60) %>% 
  nrow()

forty_to_fifty <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 40 & miles < 50) %>% 
  nrow()

thirty_to_forty <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 30 & miles < 40) %>% 
  nrow()

twenty_to_thirty <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 20 & miles < 30) %>% 
  nrow()

ten_to_twenty <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 10 & miles < 20) %>% 
  nrow()

under_ten <- location_data %>% 
  arrange(desc(miles)) %>% 
  filter(miles >= 1 & miles < 10) %>% 
  nrow()
# reversing factor levels as graph will be rotated
distance_levels <- rev(c("under ten", "ten to twenty", "twenty to thirty", "thirty to forty", "forty to fifty", "fifty to sixty", "sixty to seventy", "seventy to eighty", "eighty to ninety", "ninety to hundred", "hundred and over"))
location_distance_tibble <- tibble(under_ten, ten_to_twenty, twenty_to_thirty, thirty_to_forty, forty_to_fifty, fifty_to_sixty, sixty_to_seventy, seventy_to_eighty, eighty_to_ninety, ninety_to_hundred, hundred_and_over) %>% 
  pivot_longer(cols = (under_ten: hundred_and_over), 
               names_to = "number_that_stayed",
               values_to = "count") %>% 
  replacement_function("_", " ") %>%
  mutate(name = factor(number_that_stayed, (levels = distance_levels))) %>% 
  mutate(count = as.numeric(count)) %>% 
   ggplot() +
  geom_col(aes(x = name, y = count),fill = "#008b8b") +
  coord_flip() +
  theme_classic(base_size = 15) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(
    title = "Driving Distance to Event",
    x = "Distance (miles)",
    y = "Count"
  ) 
location_distance_tibble
```
```{r}
# a graph showing accommodation types (where more than 5 respondents stayed)
survey_data %>% 
  count(accommodation_type, sort = TRUE) %>% 
  filter(n > 5) %>% 
  mutate(name = factor(accommodation_type, levels = c("self catering", "multiple", "hotel", "hostel", "guest house/b+b", "friends/relatives", "comrie", "camping/caravan", "at home"))) %>% 
ggplot() +
  geom_col(aes(x = name, y = n),fill = "#008b8b") +
 coord_flip() +
  labs(title = "Accommodation Types",
    x = "Accommodation Types",
      y = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_classic(base_size = 25)
```

```{r}
# creating a dataframe that splits data up by population size
population_df <- survey_data %>% 
  mutate(over_10000 = population >= 10000) %>% 
  mutate(between_5000_and_10000 = population >= 5000 & population < 10000) %>% 
  mutate(between_1000_and_5000 = population >= 1000 & population < 5000) %>% 
  mutate(between_500_and_1000 = population >= 500 & population < 1000) %>% 
  mutate(under_500 = is.na(population)) %>%  
  dplyr::select(under_500, between_500_and_1000, between_1000_and_5000, between_5000_and_10000, over_10000)
```

```{r}
location_data
```

```{r}
# calculating how many respondents stayed in a location with a population of under 500
under_500_TRUE <- population_df %>% 
  filter(under_500 == TRUE) %>% 
  nrow()
``` 
```{r}
# calculating the percentage of respondents that stayed in a location with a population of under 500
under_500_TRUE/nrow(survey_data)
```
```{r}
# calculating the percentage that engaged with facebook or twitter
no <- survey_data %>% 
  filter(facebook_twitter_following == "no") %>% 
  nrow() 
yes <- survey_data %>% 
  filter(facebook_twitter_following == "yes") %>% 
  nrow() 
yes/(yes+no)
```
```{r}
# calculating the percentage of respondents who rated the Facebook and Twitter communication as "excellent" or "good"
survey_data %>%
  count(facebook_twitter_rating, sort = TRUE) %>% 
  filter(facebook_twitter_rating == "excellent" | facebook_twitter_rating == "good") 
(107 + 97)/yes
```
```{r}
printed_programme_total <- survey_data %>% 
  filter(!is.na(printed_programme_rating)) %>% 
  nrow() 
survey_data %>% 
  count(printed_programme_rating, sort = TRUE)
(364 + 241)/printed_programme_total
```

```{r}
# sorting the livestream responses into categories depending on which type(s) of the livestream they interacted with
all_livestreams <- livestream_data %>% 
  filter(livestream_after_event == "1") %>% 
  filter(livestream_competition == "1") %>% 
  filter(livestream_races == "1") %>% 
  nrow()
```
```{r}
after_event_and_competition <- livestream_data %>% 
  filter(livestream_after_event == "1") %>% 
  filter(livestream_competition == "1") %>% 
  filter(is.na(livestream_races)) %>% 
  nrow()
```
```{r}
after_event_and_races <- livestream_data %>% 
  filter(livestream_after_event == "1") %>% 
  filter(livestream_races == "1") %>% 
  filter(is.na(livestream_competition)) %>% 
  nrow()
```
```{r}
competition_and_races <- livestream_data %>% 
  filter(livestream_competition == "1") %>% 
  filter(livestream_races == "1") %>% 
  filter(is.na(livestream_after_event)) %>% 
  nrow()
```
```{r}
races <- livestream_data %>% 
  filter(is.na(livestream_after_event)) %>% 
  filter(livestream_races == "1") %>% 
  filter(is.na(livestream_competition)) %>% 
  nrow()
```
```{r}
after_event <- livestream_data %>% 
  filter(is.na(livestream_races)) %>% 
  filter(livestream_after_event == "1") %>% 
  filter(is.na(livestream_competition)) %>% 
  nrow()
```
```{r}
competition <- livestream_data %>% 
  filter(is.na(livestream_after_event)) %>% 
  filter(livestream_competition == "1") %>% 
  filter(is.na(livestream_races)) %>% 
  nrow()
```

```{r}
# graph showing the types of livestream watched 
livestream_tibble <- tibble(races, after_event, competition, competition_and_races, after_event_and_races, after_event_and_competition, all_livestreams) %>% 
  pivot_longer(cols = (races: all_livestreams), 
               names_to = "watched_livestream",
               values_to = "count") %>% 
  replacement_function("_", " ") %>%
  mutate(name = factor(watched_livestream, (levels = c("all livestreams", "competition and races", "after event and races", "after event and competition", "races", "competition", "after event")))) %>% 
  mutate(count = as.numeric(count)) %>% 
   ggplot() +
  geom_col(aes(x = name, y = count),fill = "#008b8b") +
  coord_flip() +
  theme_classic(base_size = 15) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(
    title = "Type of Livestream Watched",
    x = "Type of Livestream",
    y = "Count"
  ) 
livestream_tibble
```

